### ISSUE TITLE
Add comments section

### ISSUE THREAD

**Issue by carinilou** [kelseyneis/kelseyneis.github.io#13]
somehow give us the ability to add comments/notes to recipes from the UI of the site.

**Comment by kelseyneis** [comment]
I set up a Discourse site and now am working on [embedding it](https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963) into our recipe site. Hence the "Oops" at the bottom of the page 😅

**Comment by kelseyneis** [comment]
@carinilou @hitchhiker-42 I got the comments section working, but only in the blog post view (not the homepage, which just displays the most recent recipe). Check it out [here](http://enormousness.net/2021/04/18/vegan-lasagna/)

You should have gotten an email inviting you to Discourse, the service I set up for us. If you can't login, let me know.
