### ISSUE TITLE
Choose a domain

### ISSUE THREAD

**Issue by kelseyneis** [kelseyneis/kelseyneis.github.io#19]
We can purchase a domain at [Namecheap](https://www.namecheap.com/). What do you want it to be @carinilou @hitchhiker-42 ?

**Comment by kelseyneis** [comment]
Some ideas:

1. crabsaladclub.com (~$8/year)
2. crabsaladsociety.com (~$8/year)
3. shope.recipes (~$6/year)
4. crabsalad.recipes (~$6/year)

@carinilou @hitchhiker-42

**Comment by carinilou** [comment]
Shopesmakefood.com
Crabbyshopes.recipes
plantsandsea.recipes
plantpeople.recipes

**Comment by kelseyneis** [comment]
@carinilou going to give you the final say on what domain we go with. I need to change it today

**Comment by carinilou** [comment]
@kelseyneis let’s do eatplants.com or .recipes

backup would be Shopefamily.recipes or Shope.recipes

**Comment by kelseyneis** [comment]
For some reason, the .recipes domains are really expensive right now - same with eatplants, so I went with shopefamilyrecipes.com and this time I went with a 3-year lease.
